version: '3.8'

services:
  mongodb-test:
    image: mongo:7.0
    container_name: angioddau-mongodb-test
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: angioddau_test
    volumes:
      - mongodb_test_data:/data/db
    networks:
      - test-network

  api-test:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: angioddau-api-test
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongodb-test:27017/angioddau_test
      - PORT=5001
      - JWT_SECRET=test_jwt_secret_key_for_testing_only
    depends_on:
      - mongodb-test
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - test-network
    command: npm run test

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angioddau-frontend-test
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=test
      - NEXT_PUBLIC_API_URL=http://api-test:5001
    depends_on:
      - api-test
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - test-network
    command: npm run test

volumes:
  mongodb_test_data:

networks:
  test-network:
    driver: bridge