services:
  # Backend API Service
  - type: web
    name: an-gi-o-dau-api
    env: node
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://an-gi-o-dau-frontend-64eh.onrender.com

  # Frontend Service
  - type: web
    name: an-gi-o-dau-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://an-gi-o-dau-api-64eh.onrender.com/api